eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
    
        
  
server:
  port: 8080
  
spring:
  application:
    name: Discovery-Service-Client-Example

service:
  instance:
    name: ${random.value}     
    