eureka:
  datacenter:  Bangalore
  environment: Production
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
    register-with-eureka: false
    fetch-registry: false
        
  
server:
  port: 8071
  
spring:
  application:
    name: Discovery-Service
    