server:
  port: 8888
  
spring:
  application:
    name: Configserver
  cloud:
   config:
    server:
     git:
      uri: https://github.com/bhaveshkumar70/scf-config-repository.git      
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/