eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
    
        
  
server:
  port: 0
  
spring:
  application:
    name: Discovery-Service-Client

service:
  instance:
    name: ${random.value}     
    